# Generated by Django 4.1.3 on 2023-09-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
