# Generated by Django 4.1.3 on 2023-09-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogi', '0002_alter_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
