# Generated by Django 4.1.3 on 2023-09-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_subject_subject_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_email',
            field=models.EmailField(default=30, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
